# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WejXXAY46Vw9JLnudlUv8IRMnkbXspN
"""

import pandas as pd

file_path = '/content/Cecilia_Vidal_database.csv'
df = pd.read_csv(file_path, delimiter=';', encoding='ISO-8859-1')

df.head()