# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWSOIFWpa2rmOLK9T5pHDSVCPBh_TPk0
"""

import pandas as pd


file_path = '/content/barberias puente alto limpio.csv'
df = pd.read_csv(file_path, delimiter=';', encoding='ISO-8859-1')


df.head()